server:
  port: 9001
  tomcat:
    connection-timeout: 2s # Time to wait for an HTTP request after connection haave been made
    keep-alive-timeout: 15s # How long to keep a connection open while waiting for new HTTP requests
    threads:
      max: 50 # Maximum number of request processing threads
      min-spare: 5 # Minimum number of threads that should be kept running
    accept-count: 20
    max-http-form-post-size: 5MB

worlddev:
  greeting: Welcome to the local worldDev book catalog
  testdata:
    enabled: false

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:7000
      request-connect-timeout: 5000 # Time limit to connect to the config server
      request-read-timeout: 10000 # Time limit to read the configuration data
      retry:
        max-attempts: 3
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 5000
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: refresh # Exposes the /actuator/refresh endpoint through HTTP
