apiVersion: apps/v1
kind: Deployment
metadata:
  name: worlddev-catalog-service
  labels:
    app: worlddev-catalog-service
spec:
  replicas: 1 # How many Pod replicas should be deployed
  selector:
    matchLabels:
      app: worlddev-catalog-service
  template:
    metadata:
      labels:
        app: worlddev-catalog-service
    spec:
      containers:
        - name: worlddev-catalog-service
          image: worlddev-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"] # Makes Kubernetes wait 5 seconds before sending the SIGTERM signal to the Pod
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://worlddev-postgres:5445/worlddev_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://worlddev-configuration-service:7000
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
